# infrastructure/nginx.conf

server {
    listen 80;
    server_name dhankadpuneet6.site www.dhankadpuneet6.site;

    # Serve the compiled React frontend
    location / {
        root /home/ec2-user/web-tier/build;
        index index.html index.htm;
        try_files $uri /index.html;
    }

    # Proxy API requests to the Internal Load Balancer
    location /api/ {
        proxy_pass http://internal-App-Internal-LB-532455580.ap-south-1.elb.amazonaws.com:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Health check endpoint for the External Load Balancer
    location /health {
        default_type text/html;
        return 200 "<!DOCTYPE html><p>Web Tier Health Check</p>\n";
    }
}
